# Generated by Django 4.0.6 on 2022-07-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_alter_employee_job_title_alter_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.department'),
        ),
    ]
