# Generated by Django 4.0.6 on 2022-07-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(verbose_name='reason for overtime')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('multiplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime.multiplier')),
            ],
        ),
    ]
