# Generated by Django 4.0.6 on 2022-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
