# Generated by Django 4.0.6 on 2022-07-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='employee',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.employee'),
        ),
    ]
