# Generated by Django 4.0.6 on 2022-07-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_remove_overtime_employee_timesheet_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Overtime',
        ),
    ]
