# Generated by Django 4.0.6 on 2022-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0008_alter_timesheet_end_time_alter_timesheet_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(default='16:30'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(default='16:30'),
        ),
    ]
