# Generated by Django 4.0.6 on 2022-07-12 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0009_alter_timesheet_end_time_alter_timesheet_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(default='16:30:00'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(default='16:30:00'),
        ),
    ]
