# Generated by Django 4.0.6 on 2022-07-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0010_timesheet_created_at_timesheet_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('-created_at',)},
        ),
    ]
